name: .NET

on:
  push:
    branches: ['main']
    paths:
      - Application/**
  pull_request:
    branches: ['main']
    paths:
      - Application/**
  workflow_dispatch:

env:
  registryName: zfwyj7jpgw3hsmpnpreg.azurecr.io
  repositoryName: techboost/dotnetcoreapp
  dockerFolderPath: ./Application/src/RazorPagesTestSample
  tag: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
      - name: Build
        run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER  }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          logout: true
      - name: Docker build
        run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
      - name: Docker push
        run: docker push $registryName/$repositoryName:$tag

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: docker-build
    environment:
      name: dev
      url: https://zfwyj7jpgw3hs-dev.azurewebsites.net/
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'zfwyj7jpgw3hs-dev'
          images: $registryName/$repositoryName:$tag

  deploy-to-test:
  
    runs-on: ubuntu-latest
    needs: docker-build
    environment:
      name: test
      url: https://zfwyj7jpgw3hs-test.azurewebsites.net/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'zfwyj7jpgw3hs-test'
        images: $registryName/$repositoryName:$tag

  deploy-to-prod:
  
    runs-on: ubuntu-latest
    needs: docker-build
    environment:
      name: prod
      url: https://zfwyj7jpgw3hs-prod.azurewebsites.net/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: '{your_prefix}-prod'
        images: $registryName/$repositoryName:$tag
