name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Step 1 complete!'
      - run: echo 'Step 2 complete!'
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: mscoutermarsh/cowsays-action@v1
        with:
          text: 'Ready for prod–ship it!'
          color: 'magenta'
